# Generated by Django 5.1.1 on 2024-09-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='max_number',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamescore',
            name='operation',
            field=models.TextField(default='+'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamescore',
            name='word_length',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
